LicenseProject/Controllers/FavoriteListTOController.cs
using LicenseProject.Models;
using LicenseProject.Services;
using LicenseProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LicenseProject.Controllers
{
    public class FavoriteListTOController : Controller
    {
        private readonly Context _context;
        private readonly ITuristicObjectService _turisticObject;

        public FavoriteListTOController(Context context)
        {
            _context = context;
        }

        public ViewResult Index()
        {
            var currentUser = this.ControllerContext.HttpContext.User.Identity.Name;
            var id = _context.ApplicationUsers.FirstOrDefault(u => u.UserName == currentUser).Id;
            var items = _context.FavoriteTuristicObjects.Where(c => c.ApplicationUser.Id == id)
                           .Include(s => s.TuristicObject)
                           .ToList();
            foreach (var item in items)
                _context.FavoriteTuristicObjects.Add(item);

            var fcvm = new FavoriteCartTOViewModel
            {
                FavoriteTuristicObjects = items

            };
            return View(fcvm);
        }

        public RedirectToActionResult AddToFavoriteCart(int Id)
        {
            if (this.ControllerContext.HttpContext.User.Identity.Name != null)
            {
                var currentUser = this.ControllerContext.HttpContext.User.Identity.Name;
                var id = _context.ApplicationUsers.FirstOrDefault(u => u.UserName == currentUser).Id;
                var favoriteTuristicObject = _context.FavoriteTuristicObjects.SingleOrDefault(
                    s => s.TuristicObject.TuristicObjectId == Id && s.ApplicationUser.Id == id);
                if (favoriteTuristicObject == null)
                {
                    favoriteTuristicObject = new FavoriteTuristicObject
                    {
                        TuristicObject = _context.TuristicObjects.FirstOrDefault(r => r.TuristicObjectId == Id),
                        ApplicationUser = _context.ApplicationUsers.FirstOrDefault(u => u.UserName == currentUser)
                    };

                    _context.FavoriteTuristicObjects.Add(favoriteTuristicObject);
                }
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Page/Account/Manage/Login", new { area = "Identity" });
            }
        }
        public RedirectToActionResult RemoveFromFavoriteCart(int Id)
        {
            var currentUser = this.ControllerContext.HttpContext.User.Identity.Name;
            var id = _context.ApplicationUsers.FirstOrDefault(u => u.UserName == currentUser).Id;
            var favoriteTuristicObject = _context.FavoriteTuristicObjects.SingleOrDefault(
                s => s.TuristicObject.TuristicObjectId == Id && s.ApplicationUser.Id == id);
            if (favoriteTuristicObject != null)
            {
                _context.FavoriteTuristicObjects.Remove(favoriteTuristicObject);
            }
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

LicenseProject/Views/FavoriteListTO/Index.cshtml
@using LicenseProject.ViewModels
@model FavoriteCartTOViewModel

@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <h4>Here are all your favorite restaurants </h4>

    @foreach (var line in Model.FavoriteTuristicObjects)
    {
<div class="col-xs-4 col-sm-3 col-md-4 col-lg-3 mt-4">
    <div class="card">
        <a asp-controller="TuristicObjects" asp-action="ListInfo"></a>
        <a class="card-img-top" asp-action="TuristicObjectInfo" asp-route-id="@line.TuristicObject.TuristicObjectId">
            <img width="250px" height="200px" src="@line.TuristicObject.MainImage" />
        </a>
        <div class="card-footer">
            <h4>@line.TuristicObject.Name</h4>
            <div class="text-info"> reviews</div>
            <div class="card-text">
                <h4>
                    <a class="btn btn-success" asp-action="RemoveFromFavoriteCart" asp-controller="FavoriteListTO" asp-route-restaurantId="@line.TuristicObject.TuristicObjectId">
                        Remove from list
                    </a>

                </h4>
            </div>
        </div>
    </div>
</div>}

</body>
</html>