LicenseProject/Controllers/FavoriteListRestaurantsController.cs
using LicenseProject.Models;
using LicenseProject.Services;
using LicenseProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LicenseProject.Controllers
{
    public class FavoriteListRestaurantsController : Controller
    {
        private readonly Context _context;
        private readonly IRestaurantService _restaurant;

        public FavoriteListRestaurantsController(Context context,IRestaurantService restaurant)
        {
            _context = context;
            _restaurant = restaurant;
        }

        public ViewResult Index()
        {
            var currentUser = this.ControllerContext.HttpContext.User.Identity.Name;
            var id = _context.ApplicationUsers.FirstOrDefault(u => u.UserName == currentUser).Id;
            var items =  _context.FavoriteRestaurants.Where(c => c.ApplicationUser.Id == id)
                           .Include(s => s.Restaurant)
                           .ToList();
            foreach (var item in items)
                _context.FavoriteRestaurants.Add(item); 

            var fcvm = new FavoriteCartRestaurantsViewModel
            {
                FavoriteRestaurants = items

            };
            return View(fcvm);
        }

        public RedirectToActionResult AddToFavoriteCart(int restaurantId)
        {
            if (this.ControllerContext.HttpContext.User.Identity.Name != null) { 
                var currentUser = this.ControllerContext.HttpContext.User.Identity.Name;
                var id = _context.ApplicationUsers.FirstOrDefault(u => u.UserName == currentUser).Id;
                var favoriteRestaurant = _context.FavoriteRestaurants.SingleOrDefault(
                    s => s.Restaurant.RestaurantId == restaurantId && s.ApplicationUser.Id == id);
                if (favoriteRestaurant == null)
                {
                    favoriteRestaurant = new FavoriteRestaurant
                    {
                        Restaurant = _context.Restaurants.FirstOrDefault(r => r.RestaurantId == restaurantId),
                        ApplicationUser = _context.ApplicationUsers.FirstOrDefault(u => u.UserName == currentUser)
                    };

                    _context.FavoriteRestaurants.Add(favoriteRestaurant);
                }
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Login","Account");
            }

        }
        public RedirectToActionResult RemoveFromFavoriteCart(int restaurantId)
        {
            var currentUser = this.ControllerContext.HttpContext.User.Identity.Name;
            var id = _context.ApplicationUsers.FirstOrDefault(u => u.UserName == currentUser).Id;
            var favoriteRestaurant = _context.FavoriteRestaurants.SingleOrDefault(
                s => s.Restaurant.RestaurantId == restaurantId && s.ApplicationUser.Id == id);
            if (favoriteRestaurant != null)
            {
                _context.FavoriteRestaurants.Remove(favoriteRestaurant);
            }
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

LicenseProject/Views/FavoriteListRestaurants/Index.cshtml
@using LicenseProject.ViewModels
@model FavoriteCartRestaurantsViewModel

@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <h4>Here are all your favorite restaurants </h4>

    @foreach (var line in Model.FavoriteRestaurants)
    {
<div class="col-xs-4 col-sm-3 col-md-4 col-lg-3 mt-4">
    <div class="card">
        <a asp-controller="Restaurants" asp-action="ListInfo"></a>
        <a class="card-img-top" asp-action="RestaurantInfo" asp-route-id="@line.Restaurant.RestaurantId">
            <img width="250px" height="200px" src="@line.Restaurant.MainImage" />
        </a>
        <div class="card-footer">
            <h4>@line.Restaurant.Name</h4>
            <div class="text-info"> reviews</div>
            <div class="card-text">
                <h4>
                    <a class="btn btn-success" asp-action="RemoveFromFavoriteCart" asp-controller="FavoriteListRestaurants" asp-route-restaurantId="@line.Restaurant.RestaurantId">
                        Remove from list
                    </a>

                </h4>
            </div>
        </div>
    </div>
</div>}

</body>
</html>